alex\yamBundle\Entity\Hotel:
    type: entity
    table: hotel
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            fixed: false
        categoria:
            type: string
            nullable: true
            length: 30
            fixed: false
    lifecycleCallbacks: {  }
