alex\yamBundle\Entity\Ruta:
    type: entity
    table: ruta
    
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lugares:
            type: string
            nullable: true
            length: 20
            fixed: false
    manyToOne:
       Paquete:
            targetEntity: Paquete
            inversedBy: rutas
            joinColumn:
                name: id_paquete
                referencedColumnName: id
    lifecycleCallbacks: {  }
