alex\yamBundle\Entity\TrAccess:
    type: entity
    table: tr_access
    id:
        idProfile:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_profile
        idTab:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_tab
    fields:
        view:
            type: integer
            nullable: false
            unsigned: false
        add:
            type: integer
            nullable: false
            unsigned: false
        edit:
            type: integer
            nullable: false
            unsigned: false
        delete:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks: {  }
