alex\yamBundle\Entity\TrAlias:
    type: entity
    table: tr_alias
    uniqueConstraints:
        alias:
            columns:
                - alias
    id:
        idAlias:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_alias
            generator:
                strategy: IDENTITY
    fields:
        alias:
            type: string
            nullable: false
            length: 255
            fixed: false
        search:
            type: string
            nullable: false
            length: 255
            fixed: false
        active:
            type: boolean
            nullable: false
            default: '1'
    lifecycleCallbacks: {  }
