alex\yamBundle\Entity\TrAttributeGroupLang:
    type: entity
    table: tr_attribute_group_lang
    id:
        idAttributeGroup:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_attribute_group
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
        publicName:
            type: string
            nullable: false
            length: 64
            fixed: false
            column: public_name
    lifecycleCallbacks: {  }
