alex\yamBundle\Entity\TrAttributeGroupShop:
    type: entity
    table: tr_attribute_group_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idAttributeGroup:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_attribute_group
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
