alex\yamBundle\Entity\TrCategory:
    type: entity
    table: tr_category
    indexes:
        category_parent:
            columns:
                - id_parent
        nleftright:
            columns:
                - nleft
                - nright
        nleftrightactive:
            columns:
                - nleft
                - nright
                - active
        level_depth:
            columns:
                - level_depth
        nright:
            columns:
                - nright
        nleft:
            columns:
                - nleft
    id:
        idCategory:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_category
            generator:
                strategy: IDENTITY
    fields:
        idParent:
            type: integer
            nullable: false
            unsigned: true
            column: id_parent
        idShopDefault:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop_default
        levelDepth:
            type: boolean
            nullable: false
            default: '0'
            column: level_depth
        nleft:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
        nright:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
        active:
            type: boolean
            nullable: false
            default: '0'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        position:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
        isRootCategory:
            type: boolean
            nullable: false
            default: '0'
            column: is_root_category
    lifecycleCallbacks: {  }
