alex\yamBundle\Entity\TrCategoryLang:
    type: entity
    table: tr_category_lang
    indexes:
        category_name:
            columns:
                - name
    id:
        idCategory:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_category
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            id: true
            column: id_shop
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        linkRewrite:
            type: string
            nullable: false
            length: 128
            fixed: false
            column: link_rewrite
        metaTitle:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: meta_title
        metaKeywords:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: meta_keywords
        metaDescription:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: meta_description
    lifecycleCallbacks: {  }
