alex\yamBundle\Entity\TrCmsShop:
    type: entity
    table: tr_cms_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idCms:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_cms
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
