alex\yamBundle\Entity\TrCmsCategory:
    type: entity
    table: tr_cms_category
    indexes:
        category_parent:
            columns:
                - id_parent
    id:
        idCmsCategory:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_cms_category
            generator:
                strategy: IDENTITY
    fields:
        idParent:
            type: integer
            nullable: false
            unsigned: true
            column: id_parent
        levelDepth:
            type: boolean
            nullable: false
            default: '0'
            column: level_depth
        active:
            type: boolean
            nullable: false
            default: '0'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        position:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
    lifecycleCallbacks: {  }
