alex\yamBundle\Entity\TrCompare:
    type: entity
    table: tr_compare
    id:
        idCompare:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_compare
            generator:
                strategy: IDENTITY
    fields:
        idCustomer:
            type: integer
            nullable: false
            unsigned: true
            column: id_customer
    lifecycleCallbacks: {  }
