alex\yamBundle\Entity\TrCompareProduct:
    type: entity
    table: tr_compare_product
    id:
        idCompare:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_compare
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_product
    fields:
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
