alex\yamBundle\Entity\TrContactShop:
    type: entity
    table: tr_contact_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idContact:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_contact
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
