alex\yamBundle\Entity\TrConfigurationLang:
    type: entity
    table: tr_configuration_lang
    id:
        idConfiguration:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_configuration
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        value:
            type: text
            nullable: true
            length: 65535
            fixed: false
        dateUpd:
            type: datetime
            nullable: true
            column: date_upd
    lifecycleCallbacks: {  }
