alex\yamBundle\Entity\TrConfigurationKpi:
    type: entity
    table: tr_configuration_kpi
    indexes:
        name:
            columns:
                - name
        id_shop:
            columns:
                - id_shop
        id_shop_group:
            columns:
                - id_shop_group
    id:
        idConfigurationKpi:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_configuration_kpi
            generator:
                strategy: IDENTITY
    fields:
        idShopGroup:
            type: integer
            nullable: true
            unsigned: true
            column: id_shop_group
        idShop:
            type: integer
            nullable: true
            unsigned: true
            column: id_shop
        name:
            type: string
            nullable: false
            length: 32
            fixed: false
        value:
            type: text
            nullable: true
            length: 65535
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
