alex\yamBundle\Entity\TrConnectionsSource:
    type: entity
    table: tr_connections_source
    indexes:
        connections:
            columns:
                - id_connections
        orderby:
            columns:
                - date_add
        http_referer:
            columns:
                - http_referer
        request_uri:
            columns:
                - request_uri
    id:
        idConnectionsSource:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_connections_source
            generator:
                strategy: IDENTITY
    fields:
        idConnections:
            type: integer
            nullable: false
            unsigned: true
            column: id_connections
        httpReferer:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: http_referer
        requestUri:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: request_uri
        keywords:
            type: string
            nullable: true
            length: 255
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
