alex\yamBundle\Entity\TrCustomerThread:
    type: entity
    table: tr_customer_thread
    indexes:
        id_shop:
            columns:
                - id_shop
        id_lang:
            columns:
                - id_lang
        id_contact:
            columns:
                - id_contact
        id_customer:
            columns:
                - id_customer
        id_order:
            columns:
                - id_order
        id_product:
            columns:
                - id_product
    id:
        idCustomerThread:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_customer_thread
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop
        idLang:
            type: integer
            nullable: false
            unsigned: true
            column: id_lang
        idContact:
            type: integer
            nullable: false
            unsigned: true
            column: id_contact
        idCustomer:
            type: integer
            nullable: true
            unsigned: true
            column: id_customer
        idOrder:
            type: integer
            nullable: true
            unsigned: true
            column: id_order
        idProduct:
            type: integer
            nullable: true
            unsigned: true
            column: id_product
        status:
            type: string
            nullable: false
            length: null
            fixed: false
            default: open
        email:
            type: string
            nullable: false
            length: 128
            fixed: false
        token:
            type: string
            nullable: true
            length: 12
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
