alex\yamBundle\Entity\TrCustomerGroup:
    type: entity
    table: tr_customer_group
    indexes:
        customer_login:
            columns:
                - id_group
        id_customer:
            columns:
                - id_customer
    id:
        idCustomer:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_customer
        idGroup:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_group
    lifecycleCallbacks: {  }
