alex\yamBundle\Entity\TrCustomerMessage:
    type: entity
    table: tr_customer_message
    indexes:
        id_customer_thread:
            columns:
                - id_customer_thread
        id_employee:
            columns:
                - id_employee
    id:
        idCustomerMessage:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_customer_message
            generator:
                strategy: IDENTITY
    fields:
        idCustomerThread:
            type: integer
            nullable: true
            unsigned: false
            column: id_customer_thread
        idEmployee:
            type: integer
            nullable: true
            unsigned: true
            column: id_employee
        message:
            type: text
            nullable: false
            length: 65535
            fixed: false
        fileName:
            type: string
            nullable: true
            length: 18
            fixed: false
            column: file_name
        ipAddress:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: ip_address
        userAgent:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: user_agent
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        private:
            type: boolean
            nullable: false
            default: '0'
        read:
            type: boolean
            nullable: false
            default: '0'
    lifecycleCallbacks: {  }
