alex\yamBundle\Entity\TrEmployeeShop:
    type: entity
    table: tr_employee_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idEmployee:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_employee
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
