alex\yamBundle\Entity\TrFeatureValueLang:
    type: entity
    table: tr_feature_value_lang
    id:
        idFeatureValue:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_feature_value
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        value:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
