alex\yamBundle\Entity\TrFeatureShop:
    type: entity
    table: tr_feature_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idFeature:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_feature
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
