alex\yamBundle\Entity\TrFeatureValue:
    type: entity
    table: tr_feature_value
    indexes:
        feature:
            columns:
                - id_feature
    id:
        idFeatureValue:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_feature_value
            generator:
                strategy: IDENTITY
    fields:
        idFeature:
            type: integer
            nullable: false
            unsigned: true
            column: id_feature
        custom:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
