alex\yamBundle\Entity\TrGroupReduction:
    type: entity
    table: tr_group_reduction
    uniqueConstraints:
        id_group:
            columns:
                - id_group
                - id_category
    id:
        idGroupReduction:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_group_reduction
            generator:
                strategy: IDENTITY
    fields:
        idGroup:
            type: integer
            nullable: false
            unsigned: true
            column: id_group
        idCategory:
            type: integer
            nullable: false
            unsigned: true
            column: id_category
        reduction:
            type: decimal
            nullable: false
            precision: 4
            scale: 3
    lifecycleCallbacks: {  }
