alex\yamBundle\Entity\TrGroup:
    type: entity
    table: tr_group
    id:
        idGroup:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_group
            generator:
                strategy: IDENTITY
    fields:
        reduction:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
        priceDisplayMethod:
            type: boolean
            nullable: false
            default: '0'
            column: price_display_method
        showPrices:
            type: boolean
            nullable: false
            default: '1'
            column: show_prices
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
