alex\yamBundle\Entity\TrGuest:
    type: entity
    table: tr_guest
    indexes:
        id_customer:
            columns:
                - id_customer
        id_operating_system:
            columns:
                - id_operating_system
        id_web_browser:
            columns:
                - id_web_browser
    id:
        idGuest:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_guest
            generator:
                strategy: IDENTITY
    fields:
        idOperatingSystem:
            type: integer
            nullable: true
            unsigned: true
            column: id_operating_system
        idWebBrowser:
            type: integer
            nullable: true
            unsigned: true
            column: id_web_browser
        idCustomer:
            type: integer
            nullable: true
            unsigned: true
            column: id_customer
        javascript:
            type: boolean
            nullable: true
            default: '0'
        screenResolutionX:
            type: smallint
            nullable: true
            unsigned: true
            column: screen_resolution_x
        screenResolutionY:
            type: smallint
            nullable: true
            unsigned: true
            column: screen_resolution_y
        screenColor:
            type: boolean
            nullable: true
            column: screen_color
        sunJava:
            type: boolean
            nullable: true
            column: sun_java
        adobeFlash:
            type: boolean
            nullable: true
            column: adobe_flash
        adobeDirector:
            type: boolean
            nullable: true
            column: adobe_director
        appleQuicktime:
            type: boolean
            nullable: true
            column: apple_quicktime
        realPlayer:
            type: boolean
            nullable: true
            column: real_player
        windowsMedia:
            type: boolean
            nullable: true
            column: windows_media
        acceptLanguage:
            type: string
            nullable: true
            length: 8
            fixed: false
            column: accept_language
        mobileTheme:
            type: boolean
            nullable: false
            default: '0'
            column: mobile_theme
    lifecycleCallbacks: {  }
