alex\yamBundle\Entity\TrHookModuleExceptions:
    type: entity
    table: tr_hook_module_exceptions
    indexes:
        id_module:
            columns:
                - id_module
        id_hook:
            columns:
                - id_hook
    id:
        idHookModuleExceptions:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_hook_module_exceptions
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop
        idModule:
            type: integer
            nullable: false
            unsigned: true
            column: id_module
        idHook:
            type: integer
            nullable: false
            unsigned: true
            column: id_hook
        fileName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: file_name
    lifecycleCallbacks: {  }
