alex\yamBundle\Entity\TrImage:
    type: entity
    table: tr_image
    indexes:
        image_product:
            columns:
                - id_product
        id_product_cover:
            columns:
                - id_product
                - cover
    uniqueConstraints:
        idx_product_image:
            columns:
                - id_image
                - id_product
                - cover
    id:
        idImage:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_image
            generator:
                strategy: IDENTITY
    fields:
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            column: id_product
        position:
            type: smallint
            nullable: false
            unsigned: true
            default: '0'
        cover:
            type: boolean
            nullable: false
            default: '0'
    lifecycleCallbacks: {  }
