alex\yamBundle\Entity\TrInfo:
    type: entity
    table: tr_info
    id:
        idInfo:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_info
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            column: id_shop
    lifecycleCallbacks: {  }
