alex\yamBundle\Entity\TrLangShop:
    type: entity
    table: tr_lang_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
