alex\yamBundle\Entity\TrLayeredFilter:
    type: entity
    table: tr_layered_filter
    id:
        idLayeredFilter:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_layered_filter
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            fixed: false
        filters:
            type: text
            nullable: true
            length: 65535
            fixed: false
        nCategories:
            type: integer
            nullable: false
            unsigned: true
            column: n_categories
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
