alex\yamBundle\Entity\TrLayeredIndexableAttributeGroupLangValue:
    type: entity
    table: tr_layered_indexable_attribute_group_lang_value
    id:
        idAttributeGroup:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_attribute_group
        idLang:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_lang
    fields:
        urlName:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: url_name
        metaTitle:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: meta_title
    lifecycleCallbacks: {  }
