alex\yamBundle\Entity\TrLayeredIndexableFeatureLangValue:
    type: entity
    table: tr_layered_indexable_feature_lang_value
    id:
        idFeature:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_feature
        idLang:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_lang
    fields:
        urlName:
            type: string
            nullable: false
            length: 20
            fixed: false
            column: url_name
        metaTitle:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: meta_title
    lifecycleCallbacks: {  }
