alex\yamBundle\Entity\TrLinksmenutop:
    type: entity
    table: tr_linksmenutop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idLinksmenutop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_linksmenutop
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            column: id_shop
        newWindow:
            type: boolean
            nullable: false
            column: new_window
    lifecycleCallbacks: {  }
