alex\yamBundle\Entity\TrLog:
    type: entity
    table: tr_log
    id:
        idLog:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_log
            generator:
                strategy: IDENTITY
    fields:
        severity:
            type: boolean
            nullable: false
        errorCode:
            type: integer
            nullable: true
            unsigned: false
            column: error_code
        message:
            type: text
            nullable: false
            length: 65535
            fixed: false
        objectType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: object_type
        objectId:
            type: integer
            nullable: true
            unsigned: true
            column: object_id
        idEmployee:
            type: integer
            nullable: true
            unsigned: true
            column: id_employee
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
