alex\yamBundle\Entity\TrLugarTuristico:
    type: entity
    table: tr_lugar_turistico
    uniqueConstraints:
        id_lugar_turistico:
            columns:
                - id_lugar_turistico
    id:
        idLugarTuristico:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_lugar_turistico
        idEmployee:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_employee
    fields:
        nombre:
            type: string
            nullable: false
            length: 35
            fixed: false
        descripcionCorta:
            type: string
            nullable: false
            length: 60
            fixed: false
            column: descripcion_corta
        descripcionDetallada:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: descripcion_detallada
        leyendaCorta:
            type: string
            nullable: false
            length: 60
            fixed: false
            column: leyenda_corta
        leyendaDetallada:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: leyenda_detallada
        ubicacionExacta:
            type: string
            nullable: false
            length: 60
            fixed: false
            column: ubicacion_exacta
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        active:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
