alex\yamBundle\Entity\TrManufacturer:
    type: entity
    table: tr_manufacturer
    id:
        idManufacturer:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_manufacturer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        active:
            type: boolean
            nullable: false
            default: '0'
    lifecycleCallbacks: {  }
