alex\yamBundle\Entity\TrMessageReaded:
    type: entity
    table: tr_message_readed
    id:
        idMessage:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_message
        idEmployee:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_employee
    fields:
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
