alex\yamBundle\Entity\TrMessage:
    type: entity
    table: tr_message
    indexes:
        message_order:
            columns:
                - id_order
        id_cart:
            columns:
                - id_cart
        id_customer:
            columns:
                - id_customer
        id_employee:
            columns:
                - id_employee
    id:
        idMessage:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_message
            generator:
                strategy: IDENTITY
    fields:
        idCart:
            type: integer
            nullable: true
            unsigned: true
            column: id_cart
        idCustomer:
            type: integer
            nullable: false
            unsigned: true
            column: id_customer
        idEmployee:
            type: integer
            nullable: true
            unsigned: true
            column: id_employee
        idOrder:
            type: integer
            nullable: false
            unsigned: true
            column: id_order
        message:
            type: text
            nullable: false
            length: 65535
            fixed: false
        private:
            type: boolean
            nullable: false
            default: '1'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
