alex\yamBundle\Entity\TrModuleGroup:
    type: entity
    table: tr_module_group
    id:
        idModule:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_module
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            id: true
            column: id_shop
        idGroup:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_group
    lifecycleCallbacks: {  }
