alex\yamBundle\Entity\TrModuleCountry:
    type: entity
    table: tr_module_country
    id:
        idModule:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_module
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            id: true
            column: id_shop
        idCountry:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_country
    lifecycleCallbacks: {  }
