alex\yamBundle\Entity\TrModuleAccess:
    type: entity
    table: tr_module_access
    id:
        idProfile:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_profile
        idModule:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_module
    fields:
        view:
            type: boolean
            nullable: false
        configure:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
