alex\yamBundle\Entity\TrNewsletter:
    type: entity
    table: tr_newsletter
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop
        idShopGroup:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop_group
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        newsletterDateAdd:
            type: datetime
            nullable: true
            column: newsletter_date_add
        ipRegistrationNewsletter:
            type: string
            nullable: false
            length: 15
            fixed: false
            column: ip_registration_newsletter
        httpReferer:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: http_referer
        active:
            type: boolean
            nullable: false
            default: '0'
    lifecycleCallbacks: {  }
