alex\yamBundle\Entity\TrOperatingSystem:
    type: entity
    table: tr_operating_system
    id:
        idOperatingSystem:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_operating_system
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 64
            fixed: false
    lifecycleCallbacks: {  }
