alex\yamBundle\Entity\TrOrderInvoice:
    type: entity
    table: tr_order_invoice
    indexes:
        id_order:
            columns:
                - id_order
    id:
        idOrderInvoice:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_order_invoice
            generator:
                strategy: IDENTITY
    fields:
        idOrder:
            type: integer
            nullable: false
            unsigned: false
            column: id_order
        number:
            type: integer
            nullable: false
            unsigned: false
        deliveryNumber:
            type: integer
            nullable: false
            unsigned: false
            column: delivery_number
        deliveryDate:
            type: datetime
            nullable: true
            column: delivery_date
        totalDiscountTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_discount_tax_excl
        totalDiscountTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_discount_tax_incl
        totalPaidTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_paid_tax_excl
        totalPaidTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_paid_tax_incl
        totalProducts:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_products
        totalProductsWt:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_products_wt
        totalShippingTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_shipping_tax_excl
        totalShippingTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_shipping_tax_incl
        shippingTaxComputationMethod:
            type: integer
            nullable: false
            unsigned: true
            column: shipping_tax_computation_method
        totalWrappingTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_wrapping_tax_excl
        totalWrappingTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_wrapping_tax_incl
        note:
            type: text
            nullable: true
            length: 65535
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
