alex\yamBundle\Entity\TrOrderReturn:
    type: entity
    table: tr_order_return
    indexes:
        order_return_customer:
            columns:
                - id_customer
        id_order:
            columns:
                - id_order
    id:
        idOrderReturn:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_order_return
            generator:
                strategy: IDENTITY
    fields:
        idCustomer:
            type: integer
            nullable: false
            unsigned: true
            column: id_customer
        idOrder:
            type: integer
            nullable: false
            unsigned: true
            column: id_order
        state:
            type: boolean
            nullable: false
            default: '1'
        question:
            type: text
            nullable: false
            length: 65535
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
