alex\yamBundle\Entity\TrOrderDetail:
    type: entity
    table: tr_order_detail
    indexes:
        order_detail_order:
            columns:
                - id_order
        product_id:
            columns:
                - product_id
        product_attribute_id:
            columns:
                - product_attribute_id
        id_order_id_order_detail:
            columns:
                - id_order
                - id_order_detail
    id:
        idOrderDetail:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_order_detail
            generator:
                strategy: IDENTITY
    fields:
        idOrder:
            type: integer
            nullable: false
            unsigned: true
            column: id_order
        idOrderInvoice:
            type: integer
            nullable: true
            unsigned: false
            column: id_order_invoice
        idWarehouse:
            type: integer
            nullable: true
            unsigned: true
            default: '0'
            column: id_warehouse
        idShop:
            type: integer
            nullable: false
            unsigned: true
            column: id_shop
        productId:
            type: integer
            nullable: false
            unsigned: true
            column: product_id
        productAttributeId:
            type: integer
            nullable: true
            unsigned: true
            column: product_attribute_id
        productName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: product_name
        productQuantity:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: product_quantity
        productQuantityInStock:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: product_quantity_in_stock
        productQuantityRefunded:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: product_quantity_refunded
        productQuantityReturn:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: product_quantity_return
        productQuantityReinjected:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: product_quantity_reinjected
        productPrice:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: product_price
        reductionPercent:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            default: '0.00'
            column: reduction_percent
        reductionAmount:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: reduction_amount
        reductionAmountTaxIncl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: reduction_amount_tax_incl
        reductionAmountTaxExcl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: reduction_amount_tax_excl
        groupReduction:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            default: '0.00'
            column: group_reduction
        productQuantityDiscount:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: product_quantity_discount
        productEan13:
            type: string
            nullable: true
            length: 13
            fixed: false
            column: product_ean13
        productUpc:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: product_upc
        productReference:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: product_reference
        productSupplierReference:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: product_supplier_reference
        productWeight:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            column: product_weight
        taxComputationMethod:
            type: boolean
            nullable: false
            default: '0'
            column: tax_computation_method
        taxName:
            type: string
            nullable: false
            length: 16
            fixed: false
            column: tax_name
        taxRate:
            type: decimal
            nullable: false
            precision: 10
            scale: 3
            default: '0.000'
            column: tax_rate
        ecotax:
            type: decimal
            nullable: false
            precision: 21
            scale: 6
            default: '0.000000'
        ecotaxTaxRate:
            type: decimal
            nullable: false
            precision: 5
            scale: 3
            default: '0.000'
            column: ecotax_tax_rate
        discountQuantityApplied:
            type: boolean
            nullable: false
            default: '0'
            column: discount_quantity_applied
        downloadHash:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: download_hash
        downloadNb:
            type: integer
            nullable: true
            unsigned: true
            default: '0'
            column: download_nb
        downloadDeadline:
            type: datetime
            nullable: true
            column: download_deadline
        totalPriceTaxIncl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: total_price_tax_incl
        totalPriceTaxExcl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: total_price_tax_excl
        unitPriceTaxIncl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: unit_price_tax_incl
        unitPriceTaxExcl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: unit_price_tax_excl
        totalShippingPriceTaxIncl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: total_shipping_price_tax_incl
        totalShippingPriceTaxExcl:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: total_shipping_price_tax_excl
        purchaseSupplierPrice:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: purchase_supplier_price
        originalProductPrice:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: original_product_price
    lifecycleCallbacks: {  }
