alex\yamBundle\Entity\TrOrderDetailTax:
    type: entity
    table: tr_order_detail_tax
    indexes:
        id_order_detail:
            columns:
                - id_order_detail
        id_tax:
            columns:
                - id_tax
    id:
        idOrderDetail:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_order_detail
        idTax:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_tax
    fields:
        unitAmount:
            type: decimal
            nullable: false
            precision: 16
            scale: 6
            default: '0.000000'
            column: unit_amount
        totalAmount:
            type: decimal
            nullable: false
            precision: 16
            scale: 6
            default: '0.000000'
            column: total_amount
    lifecycleCallbacks: {  }
