alex\yamBundle\Entity\TrOrderMessage:
    type: entity
    table: tr_order_message
    id:
        idOrderMessage:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_order_message
            generator:
                strategy: IDENTITY
    fields:
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
