alex\yamBundle\Entity\TrOrderSlip:
    type: entity
    table: tr_order_slip
    indexes:
        order_slip_customer:
            columns:
                - id_customer
        id_order:
            columns:
                - id_order
    id:
        idOrderSlip:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_order_slip
            generator:
                strategy: IDENTITY
    fields:
        conversionRate:
            type: decimal
            nullable: false
            precision: 13
            scale: 6
            default: '1.000000'
            column: conversion_rate
        idCustomer:
            type: integer
            nullable: false
            unsigned: true
            column: id_customer
        idOrder:
            type: integer
            nullable: false
            unsigned: true
            column: id_order
        shippingCost:
            type: boolean
            nullable: false
            default: '0'
            column: shipping_cost
        amount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        shippingCostAmount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: shipping_cost_amount
        partial:
            type: boolean
            nullable: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
