alex\yamBundle\Entity\TrOrderInvoiceTax:
    type: entity
    table: tr_order_invoice_tax
    indexes:
        id_tax:
            columns:
                - id_tax
    id:
        idOrderInvoice:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_order_invoice
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 15
            fixed: false
        idTax:
            type: integer
            nullable: false
            unsigned: false
            column: id_tax
        amount:
            type: decimal
            nullable: false
            precision: 10
            scale: 6
            default: '0.000000'
    lifecycleCallbacks: {  }
