alex\yamBundle\Entity\TrOrders:
    type: entity
    table: tr_orders
    indexes:
        id_customer:
            columns:
                - id_customer
        id_cart:
            columns:
                - id_cart
        invoice_number:
            columns:
                - invoice_number
        id_carrier:
            columns:
                - id_carrier
        id_lang:
            columns:
                - id_lang
        id_currency:
            columns:
                - id_currency
        id_address_delivery:
            columns:
                - id_address_delivery
        id_address_invoice:
            columns:
                - id_address_invoice
        id_shop_group:
            columns:
                - id_shop_group
        current_state:
            columns:
                - current_state
        id_shop:
            columns:
                - id_shop
        date_add:
            columns:
                - date_add
    id:
        idOrder:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_order
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: string
            nullable: true
            length: 9
            fixed: false
        idShopGroup:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop_group
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop
        idCarrier:
            type: integer
            nullable: false
            unsigned: true
            column: id_carrier
        idLang:
            type: integer
            nullable: false
            unsigned: true
            column: id_lang
        idCustomer:
            type: integer
            nullable: true
            unsigned: false
            column: id_customer
        idCart:
            type: integer
            nullable: false
            unsigned: true
            column: id_cart
        idCurrency:
            type: integer
            nullable: false
            unsigned: true
            column: id_currency
        idAddressDelivery:
            type: integer
            nullable: true
            unsigned: false
            column: id_address_delivery
        idAddressInvoice:
            type: integer
            nullable: true
            unsigned: false
            column: id_address_invoice
        currentState:
            type: integer
            nullable: false
            unsigned: true
            column: current_state
        secureKey:
            type: string
            nullable: true
            length: 32
            fixed: false
            default: '-1'
            column: secure_key
        payment:
            type: string
            nullable: false
            length: 255
            fixed: false
        conversionRate:
            type: decimal
            nullable: false
            precision: 13
            scale: 6
            default: '1.000000'
            column: conversion_rate
        module:
            type: string
            nullable: true
            length: 255
            fixed: false
        recyclable:
            type: boolean
            nullable: false
            default: '0'
        gift:
            type: boolean
            nullable: false
            default: '0'
        giftMessage:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: gift_message
        mobileTheme:
            type: boolean
            nullable: false
            default: '0'
            column: mobile_theme
        shippingNumber:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: shipping_number
        totalDiscounts:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_discounts
        totalDiscountsTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_discounts_tax_incl
        totalDiscountsTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_discounts_tax_excl
        totalPaid:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_paid
        totalPaidTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_paid_tax_incl
        totalPaidTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_paid_tax_excl
        totalPaidReal:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_paid_real
        totalProducts:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_products
        totalProductsWt:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_products_wt
        totalShipping:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_shipping
        totalShippingTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_shipping_tax_incl
        totalShippingTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_shipping_tax_excl
        carrierTaxRate:
            type: decimal
            nullable: false
            precision: 10
            scale: 3
            default: '0.000'
            column: carrier_tax_rate
        totalWrapping:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_wrapping
        totalWrappingTaxIncl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_wrapping_tax_incl
        totalWrappingTaxExcl:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            default: '0.00'
            column: total_wrapping_tax_excl
        invoiceNumber:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: invoice_number
        deliveryNumber:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: delivery_number
        invoiceDate:
            type: datetime
            nullable: false
            column: invoice_date
        deliveryDate:
            type: datetime
            nullable: false
            column: delivery_date
        valid:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        comanda:
            type: integer
            nullable: true
            unsigned: false
        idMeza:
            type: integer
            nullable: true
            unsigned: false
            column: id_meza
        payTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: pay_total
        idCajaDetalle:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: id_caja_detalle
    lifecycleCallbacks: {  }
