alex\yamBundle\Entity\TrProfileLang:
    type: entity
    table: tr_profile_lang
    id:
        idProfile:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_profile
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
    lifecycleCallbacks: {  }
