alex\yamBundle\Entity\TrProduct:
    type: entity
    table: tr_product
    indexes:
        product_supplier:
            columns:
                - id_supplier
        product_manufacturer:
            columns:
                - id_manufacturer
        id_category_default:
            columns:
                - id_category_default
        indexed:
            columns:
                - indexed
        date_add:
            columns:
                - date_add
    id:
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_product
            generator:
                strategy: IDENTITY
    fields:
        idSupplier:
            type: integer
            nullable: true
            unsigned: true
            column: id_supplier
        idManufacturer:
            type: integer
            nullable: true
            unsigned: true
            column: id_manufacturer
        idCategoryDefault:
            type: integer
            nullable: true
            unsigned: true
            column: id_category_default
        idShopDefault:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop_default
        idTaxRulesGroup:
            type: integer
            nullable: false
            unsigned: true
            column: id_tax_rules_group
        onSale:
            type: boolean
            nullable: false
            default: '0'
            column: on_sale
        onlineOnly:
            type: boolean
            nullable: false
            default: '0'
            column: online_only
        ean13:
            type: string
            nullable: true
            length: 13
            fixed: false
        upc:
            type: string
            nullable: true
            length: 12
            fixed: false
        ecotax:
            type: decimal
            nullable: false
            precision: 17
            scale: 6
            default: '0.000000'
        quantity:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        minimalQuantity:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: minimal_quantity
        price:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
        wholesalePrice:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: wholesale_price
        unity:
            type: string
            nullable: true
            length: 255
            fixed: false
        unitPriceRatio:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
            column: unit_price_ratio
        additionalShippingCost:
            type: decimal
            nullable: false
            precision: 20
            scale: 2
            default: '0.00'
            column: additional_shipping_cost
        reference:
            type: string
            nullable: true
            length: 32
            fixed: false
        supplierReference:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: supplier_reference
        location:
            type: string
            nullable: true
            length: 64
            fixed: false
        width:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
        height:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
        depth:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
        weight:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
            default: '0.000000'
        outOfStock:
            type: integer
            nullable: false
            unsigned: true
            default: '2'
            column: out_of_stock
        quantityDiscount:
            type: boolean
            nullable: true
            default: '0'
            column: quantity_discount
        customizable:
            type: boolean
            nullable: false
            default: '0'
        uploadableFiles:
            type: boolean
            nullable: false
            default: '0'
            column: uploadable_files
        textFields:
            type: boolean
            nullable: false
            default: '0'
            column: text_fields
        active:
            type: boolean
            nullable: false
            default: '0'
        redirectType:
            type: string
            nullable: false
            length: null
            fixed: false
            default: ''
            column: redirect_type
        idProductRedirected:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: id_product_redirected
        availableForOrder:
            type: boolean
            nullable: false
            default: '1'
            column: available_for_order
        availableDate:
            type: date
            nullable: false
            column: available_date
        condition:
            type: string
            nullable: false
            length: null
            fixed: false
            default: new
        showPrice:
            type: boolean
            nullable: false
            default: '1'
            column: show_price
        indexed:
            type: boolean
            nullable: false
            default: '0'
        visibility:
            type: string
            nullable: false
            length: null
            fixed: false
            default: both
        cacheIsPack:
            type: boolean
            nullable: false
            default: '0'
            column: cache_is_pack
        cacheHasAttachments:
            type: boolean
            nullable: false
            default: '0'
            column: cache_has_attachments
        isVirtual:
            type: boolean
            nullable: false
            default: '0'
            column: is_virtual
        cacheDefaultAttribute:
            type: integer
            nullable: true
            unsigned: true
            column: cache_default_attribute
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        advancedStockManagement:
            type: boolean
            nullable: false
            default: '0'
            column: advanced_stock_management
    lifecycleCallbacks: {  }
