alex\yamBundle\Entity\TrProductDownload:
    type: entity
    table: tr_product_download
    indexes:
        product_active:
            columns:
                - id_product
                - active
    id:
        idProductDownload:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_product_download
            generator:
                strategy: IDENTITY
    fields:
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            column: id_product
        displayFilename:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: display_filename
        filename:
            type: string
            nullable: true
            length: 255
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateExpiration:
            type: datetime
            nullable: true
            column: date_expiration
        nbDaysAccessible:
            type: integer
            nullable: true
            unsigned: true
            column: nb_days_accessible
        nbDownloadable:
            type: integer
            nullable: true
            unsigned: true
            default: '1'
            column: nb_downloadable
        active:
            type: boolean
            nullable: false
            default: '1'
        isShareable:
            type: boolean
            nullable: false
            default: '0'
            column: is_shareable
    lifecycleCallbacks: {  }
