alex\yamBundle\Entity\TrProductSale:
    type: entity
    table: tr_product_sale
    id:
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_product
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
        saleNbr:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: sale_nbr
        dateUpd:
            type: date
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
