alex\yamBundle\Entity\TrRangePrice:
    type: entity
    table: tr_range_price
    uniqueConstraints:
        id_carrier:
            columns:
                - id_carrier
                - delimiter1
                - delimiter2
    id:
        idRangePrice:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_range_price
            generator:
                strategy: IDENTITY
    fields:
        idCarrier:
            type: integer
            nullable: false
            unsigned: true
            column: id_carrier
        delimiter1:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
        delimiter2:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
    lifecycleCallbacks: {  }
