alex\yamBundle\Entity\TrRangeWeight:
    type: entity
    table: tr_range_weight
    uniqueConstraints:
        id_carrier:
            columns:
                - id_carrier
                - delimiter1
                - delimiter2
    id:
        idRangeWeight:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_range_weight
            generator:
                strategy: IDENTITY
    fields:
        idCarrier:
            type: integer
            nullable: false
            unsigned: true
            column: id_carrier
        delimiter1:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
        delimiter2:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
    lifecycleCallbacks: {  }
