alex\yamBundle\Entity\TrReferrer:
    type: entity
    table: tr_referrer
    id:
        idReferrer:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_referrer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            fixed: false
        passwd:
            type: string
            nullable: true
            length: 32
            fixed: false
        httpRefererRegexp:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: http_referer_regexp
        httpRefererLike:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: http_referer_like
        requestUriRegexp:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: request_uri_regexp
        requestUriLike:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: request_uri_like
        httpRefererRegexpNot:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: http_referer_regexp_not
        httpRefererLikeNot:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: http_referer_like_not
        requestUriRegexpNot:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: request_uri_regexp_not
        requestUriLikeNot:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: request_uri_like_not
        baseFee:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            default: '0.00'
            column: base_fee
        percentFee:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            default: '0.00'
            column: percent_fee
        clickFee:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            default: '0.00'
            column: click_fee
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
