alex\yamBundle\Entity\TrSekeyword:
    type: entity
    table: tr_sekeyword
    id:
        idSekeyword:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_sekeyword
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop
        idShopGroup:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop_group
        keyword:
            type: string
            nullable: false
            length: 256
            fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
