alex\yamBundle\Entity\TrStockAvailable:
    type: entity
    table: tr_stock_available
    indexes:
        id_shop:
            columns:
                - id_shop
        id_shop_group:
            columns:
                - id_shop_group
        id_product:
            columns:
                - id_product
        id_product_attribute:
            columns:
                - id_product_attribute
    uniqueConstraints:
        product_sqlstock:
            columns:
                - id_product
                - id_product_attribute
                - id_shop
                - id_shop_group
    id:
        idStockAvailable:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_stock_available
            generator:
                strategy: IDENTITY
    fields:
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            column: id_product
        idProductAttribute:
            type: integer
            nullable: false
            unsigned: true
            column: id_product_attribute
        idShop:
            type: integer
            nullable: false
            unsigned: true
            column: id_shop
        idShopGroup:
            type: integer
            nullable: false
            unsigned: true
            column: id_shop_group
        quantity:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        dependsOnStock:
            type: boolean
            nullable: false
            default: '0'
            column: depends_on_stock
        outOfStock:
            type: boolean
            nullable: false
            default: '0'
            column: out_of_stock
    lifecycleCallbacks: {  }
