alex\yamBundle\Entity\TrStockMvt:
    type: entity
    table: tr_stock_mvt
    indexes:
        id_stock:
            columns:
                - id_stock
        id_stock_mvt_reason:
            columns:
                - id_stock_mvt_reason
    id:
        idStockMvt:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            column: id_stock_mvt
            generator:
                strategy: IDENTITY
    fields:
        idStock:
            type: integer
            nullable: false
            unsigned: true
            column: id_stock
        idOrder:
            type: integer
            nullable: true
            unsigned: true
            column: id_order
        idSupplyOrder:
            type: integer
            nullable: true
            unsigned: true
            column: id_supply_order
        idStockMvtReason:
            type: integer
            nullable: false
            unsigned: true
            column: id_stock_mvt_reason
        idEmployee:
            type: integer
            nullable: false
            unsigned: true
            column: id_employee
        employeeLastname:
            type: string
            nullable: true
            length: 32
            fixed: false
            default: ''
            column: employee_lastname
        employeeFirstname:
            type: string
            nullable: true
            length: 32
            fixed: false
            default: ''
            column: employee_firstname
        physicalQuantity:
            type: integer
            nullable: false
            unsigned: true
            column: physical_quantity
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        sign:
            type: boolean
            nullable: false
            default: '1'
        priceTe:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: price_te
        lastWa:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: last_wa
        currentWa:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: current_wa
        referer:
            type: bigint
            nullable: true
            unsigned: true
    lifecycleCallbacks: {  }
