alex\yamBundle\Entity\TrStatssearch:
    type: entity
    table: tr_statssearch
    id:
        idStatssearch:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_statssearch
            generator:
                strategy: IDENTITY
    fields:
        idShop:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop
        idShopGroup:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
            column: id_shop_group
        keywords:
            type: string
            nullable: false
            length: 255
            fixed: false
        results:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
