alex\yamBundle\Entity\TrStockMvtReason:
    type: entity
    table: tr_stock_mvt_reason
    id:
        idStockMvtReason:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_stock_mvt_reason
            generator:
                strategy: IDENTITY
    fields:
        sign:
            type: boolean
            nullable: false
            default: '1'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
        deleted:
            type: boolean
            nullable: false
            default: '0'
    lifecycleCallbacks: {  }
