alex\yamBundle\Entity\TrStore:
    type: entity
    table: tr_store
    id:
        idStore:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_store
            generator:
                strategy: IDENTITY
    fields:
        idCountry:
            type: integer
            nullable: false
            unsigned: true
            column: id_country
        idState:
            type: integer
            nullable: true
            unsigned: true
            column: id_state
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
        address1:
            type: string
            nullable: false
            length: 128
            fixed: false
        address2:
            type: string
            nullable: true
            length: 128
            fixed: false
        city:
            type: string
            nullable: false
            length: 64
            fixed: false
        postcode:
            type: string
            nullable: false
            length: 12
            fixed: false
        latitude:
            type: decimal
            nullable: true
            precision: 13
            scale: 8
        longitude:
            type: decimal
            nullable: true
            precision: 13
            scale: 8
        hours:
            type: string
            nullable: true
            length: 254
            fixed: false
        phone:
            type: string
            nullable: true
            length: 16
            fixed: false
        fax:
            type: string
            nullable: true
            length: 16
            fixed: false
        email:
            type: string
            nullable: true
            length: 128
            fixed: false
        note:
            type: text
            nullable: true
            length: 65535
            fixed: false
        active:
            type: boolean
            nullable: false
            default: '0'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
