alex\yamBundle\Entity\TrSupplierLang:
    type: entity
    table: tr_supplier_lang
    id:
        idSupplier:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_supplier
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        metaTitle:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: meta_title
        metaKeywords:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: meta_keywords
        metaDescription:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: meta_description
    lifecycleCallbacks: {  }
