alex\yamBundle\Entity\TrSupplyOrderReceiptHistory:
    type: entity
    table: tr_supply_order_receipt_history
    indexes:
        id_supply_order_detail:
            columns:
                - id_supply_order_detail
        id_supply_order_state:
            columns:
                - id_supply_order_state
    id:
        idSupplyOrderReceiptHistory:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_supply_order_receipt_history
            generator:
                strategy: IDENTITY
    fields:
        idSupplyOrderDetail:
            type: integer
            nullable: false
            unsigned: true
            column: id_supply_order_detail
        idEmployee:
            type: integer
            nullable: false
            unsigned: true
            column: id_employee
        employeeLastname:
            type: string
            nullable: true
            length: 32
            fixed: false
            default: ''
            column: employee_lastname
        employeeFirstname:
            type: string
            nullable: true
            length: 32
            fixed: false
            default: ''
            column: employee_firstname
        idSupplyOrderState:
            type: integer
            nullable: false
            unsigned: true
            column: id_supply_order_state
        quantity:
            type: integer
            nullable: false
            unsigned: true
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
