alex\yamBundle\Entity\TrSupplierShop:
    type: entity
    table: tr_supplier_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idSupplier:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_supplier
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
