alex\yamBundle\Entity\TrSupplyOrderDetail:
    type: entity
    table: tr_supply_order_detail
    indexes:
        id_supply_order:
            columns:
                - id_supply_order
        id_product:
            columns:
                - id_product
        id_product_attribute:
            columns:
                - id_product_attribute
        id_product_product_attribute:
            columns:
                - id_product
                - id_product_attribute
    id:
        idSupplyOrderDetail:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_supply_order_detail
            generator:
                strategy: IDENTITY
    fields:
        idSupplyOrder:
            type: integer
            nullable: false
            unsigned: true
            column: id_supply_order
        idCurrency:
            type: integer
            nullable: false
            unsigned: true
            column: id_currency
        idProduct:
            type: integer
            nullable: false
            unsigned: true
            column: id_product
        idProductAttribute:
            type: integer
            nullable: false
            unsigned: true
            column: id_product_attribute
        reference:
            type: string
            nullable: false
            length: 32
            fixed: false
        supplierReference:
            type: string
            nullable: false
            length: 32
            fixed: false
            column: supplier_reference
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
        ean13:
            type: string
            nullable: true
            length: 13
            fixed: false
        upc:
            type: string
            nullable: true
            length: 12
            fixed: false
        exchangeRate:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: exchange_rate
        unitPriceTe:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: unit_price_te
        quantityExpected:
            type: integer
            nullable: false
            unsigned: true
            column: quantity_expected
        quantityReceived:
            type: integer
            nullable: false
            unsigned: true
            column: quantity_received
        priceTe:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: price_te
        discountRate:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: discount_rate
        discountValueTe:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: discount_value_te
        priceWithDiscountTe:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: price_with_discount_te
        taxRate:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: tax_rate
        taxValue:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: tax_value
        priceTi:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: price_ti
        taxValueWithOrderDiscount:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: tax_value_with_order_discount
        priceWithOrderDiscountTe:
            type: decimal
            nullable: true
            precision: 20
            scale: 6
            default: '0.000000'
            column: price_with_order_discount_te
    lifecycleCallbacks: {  }
