alex\yamBundle\Entity\TrTabLang:
    type: entity
    table: tr_tab_lang
    id:
        idTab:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_tab
        idLang:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_lang
    fields:
        name:
            type: string
            nullable: true
            length: 64
            fixed: false
    lifecycleCallbacks: {  }
