alex\yamBundle\Entity\TrTheme:
    type: entity
    table: tr_theme
    id:
        idTheme:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_theme
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            fixed: false
        directory:
            type: string
            nullable: false
            length: 64
            fixed: false
        responsive:
            type: boolean
            nullable: false
            default: '0'
        defaultLeftColumn:
            type: boolean
            nullable: false
            default: '0'
            column: default_left_column
        defaultRightColumn:
            type: boolean
            nullable: false
            default: '0'
            column: default_right_column
        productPerPage:
            type: integer
            nullable: false
            unsigned: true
            column: product_per_page
    lifecycleCallbacks: {  }
