alex\yamBundle\Entity\TrWebserviceAccount:
    type: entity
    table: tr_webservice_account
    indexes:
        key:
            columns:
                - key
    id:
        idWebserviceAccount:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_webservice_account
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 32
            fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        className:
            type: string
            nullable: false
            length: 50
            fixed: false
            default: WebserviceRequest
            column: class_name
        isModule:
            type: boolean
            nullable: false
            default: '0'
            column: is_module
        moduleName:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: module_name
        active:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
