alex\yamBundle\Entity\TrWebserviceAccountShop:
    type: entity
    table: tr_webservice_account_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idWebserviceAccount:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_webservice_account
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
