alex\yamBundle\Entity\TrZoneShop:
    type: entity
    table: tr_zone_shop
    indexes:
        id_shop:
            columns:
                - id_shop
    id:
        idZone:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_zone
        idShop:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_shop
    lifecycleCallbacks: {  }
