<?php

namespace alex\yamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * duracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class duracionRepository extends EntityRepository
{
}
