<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrOrderInvoice extends \alex\yamBundle\Entity\TrOrderInvoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'idOrderInvoice', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'idOrder', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'number', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'deliveryNumber', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'deliveryDate', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalDiscountTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalDiscountTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalPaidTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalPaidTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalProducts', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalProductsWt', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalShippingTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalShippingTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'shippingTaxComputationMethod', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalWrappingTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalWrappingTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'note', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'dateAdd');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'idOrderInvoice', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'idOrder', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'number', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'deliveryNumber', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'deliveryDate', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalDiscountTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalDiscountTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalPaidTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalPaidTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalProducts', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalProductsWt', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalShippingTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalShippingTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'shippingTaxComputationMethod', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalWrappingTaxExcl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'totalWrappingTaxIncl', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'note', '' . "\0" . 'alex\\yamBundle\\Entity\\TrOrderInvoice' . "\0" . 'dateAdd');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrOrderInvoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrderInvoice()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOrderInvoice();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrderInvoice', array());

        return parent::getIdOrderInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOrder($idOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOrder', array($idOrder));

        return parent::setIdOrder($idOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrder', array());

        return parent::getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryNumber($deliveryNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryNumber', array($deliveryNumber));

        return parent::setDeliveryNumber($deliveryNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryNumber', array());

        return parent::getDeliveryNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryDate($deliveryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryDate', array($deliveryDate));

        return parent::setDeliveryDate($deliveryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryDate', array());

        return parent::getDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalDiscountTaxExcl($totalDiscountTaxExcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalDiscountTaxExcl', array($totalDiscountTaxExcl));

        return parent::setTotalDiscountTaxExcl($totalDiscountTaxExcl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalDiscountTaxExcl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalDiscountTaxExcl', array());

        return parent::getTotalDiscountTaxExcl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalDiscountTaxIncl($totalDiscountTaxIncl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalDiscountTaxIncl', array($totalDiscountTaxIncl));

        return parent::setTotalDiscountTaxIncl($totalDiscountTaxIncl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalDiscountTaxIncl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalDiscountTaxIncl', array());

        return parent::getTotalDiscountTaxIncl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPaidTaxExcl($totalPaidTaxExcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPaidTaxExcl', array($totalPaidTaxExcl));

        return parent::setTotalPaidTaxExcl($totalPaidTaxExcl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPaidTaxExcl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPaidTaxExcl', array());

        return parent::getTotalPaidTaxExcl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPaidTaxIncl($totalPaidTaxIncl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPaidTaxIncl', array($totalPaidTaxIncl));

        return parent::setTotalPaidTaxIncl($totalPaidTaxIncl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPaidTaxIncl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPaidTaxIncl', array());

        return parent::getTotalPaidTaxIncl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalProducts($totalProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalProducts', array($totalProducts));

        return parent::setTotalProducts($totalProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalProducts', array());

        return parent::getTotalProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalProductsWt($totalProductsWt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalProductsWt', array($totalProductsWt));

        return parent::setTotalProductsWt($totalProductsWt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalProductsWt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalProductsWt', array());

        return parent::getTotalProductsWt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalShippingTaxExcl($totalShippingTaxExcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalShippingTaxExcl', array($totalShippingTaxExcl));

        return parent::setTotalShippingTaxExcl($totalShippingTaxExcl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalShippingTaxExcl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalShippingTaxExcl', array());

        return parent::getTotalShippingTaxExcl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalShippingTaxIncl($totalShippingTaxIncl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalShippingTaxIncl', array($totalShippingTaxIncl));

        return parent::setTotalShippingTaxIncl($totalShippingTaxIncl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalShippingTaxIncl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalShippingTaxIncl', array());

        return parent::getTotalShippingTaxIncl();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingTaxComputationMethod($shippingTaxComputationMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingTaxComputationMethod', array($shippingTaxComputationMethod));

        return parent::setShippingTaxComputationMethod($shippingTaxComputationMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTaxComputationMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTaxComputationMethod', array());

        return parent::getShippingTaxComputationMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalWrappingTaxExcl($totalWrappingTaxExcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalWrappingTaxExcl', array($totalWrappingTaxExcl));

        return parent::setTotalWrappingTaxExcl($totalWrappingTaxExcl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalWrappingTaxExcl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalWrappingTaxExcl', array());

        return parent::getTotalWrappingTaxExcl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalWrappingTaxIncl($totalWrappingTaxIncl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalWrappingTaxIncl', array($totalWrappingTaxIncl));

        return parent::setTotalWrappingTaxIncl($totalWrappingTaxIncl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalWrappingTaxIncl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalWrappingTaxIncl', array());

        return parent::getTotalWrappingTaxIncl();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdd($dateAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdd', array($dateAdd));

        return parent::setDateAdd($dateAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdd', array());

        return parent::getDateAdd();
    }

}
