<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrImageType extends \alex\yamBundle\Entity\TrImageType implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'idImageType', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'name', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'width', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'height', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'products', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'categories', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'manufacturers', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'suppliers', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'scenes', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'stores');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'idImageType', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'name', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'width', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'height', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'products', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'categories', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'manufacturers', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'suppliers', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'scenes', '' . "\0" . 'alex\\yamBundle\\Entity\\TrImageType' . "\0" . 'stores');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrImageType $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdImageType()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdImageType();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdImageType', array());

        return parent::getIdImageType();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth($width)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', array($width));

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', array());

        return parent::getWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', array($height));

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', array());

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducts($products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducts', array($products));

        return parent::setProducts($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories($categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', array($categories));

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturers($manufacturers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturers', array($manufacturers));

        return parent::setManufacturers($manufacturers);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturers', array());

        return parent::getManufacturers();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuppliers($suppliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuppliers', array($suppliers));

        return parent::setSuppliers($suppliers);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuppliers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuppliers', array());

        return parent::getSuppliers();
    }

    /**
     * {@inheritDoc}
     */
    public function setScenes($scenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScenes', array($scenes));

        return parent::setScenes($scenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getScenes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScenes', array());

        return parent::getScenes();
    }

    /**
     * {@inheritDoc}
     */
    public function setStores($stores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStores', array($stores));

        return parent::setStores($stores);
    }

    /**
     * {@inheritDoc}
     */
    public function getStores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStores', array());

        return parent::getStores();
    }

}
