<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrLugarVuelo extends \alex\yamBundle\Entity\TrLugarVuelo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'idLugares', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'idDetalleCoti', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'fechaVuelo', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'numVuelo', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'lPartida', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'lLlegada', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'hSalida', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'hLlegada', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'dateAdd', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'dateUpd');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'idLugares', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'idDetalleCoti', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'fechaVuelo', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'numVuelo', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'lPartida', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'lLlegada', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'hSalida', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'hLlegada', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'dateAdd', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLugarVuelo' . "\0" . 'dateUpd');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrLugarVuelo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdLugares()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLugares();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLugares', array());

        return parent::getIdLugares();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDetalleCoti($idDetalleCoti)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDetalleCoti', array($idDetalleCoti));

        return parent::setIdDetalleCoti($idDetalleCoti);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDetalleCoti()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDetalleCoti', array());

        return parent::getIdDetalleCoti();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaVuelo($fechaVuelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaVuelo', array($fechaVuelo));

        return parent::setFechaVuelo($fechaVuelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaVuelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaVuelo', array());

        return parent::getFechaVuelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumVuelo($numVuelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumVuelo', array($numVuelo));

        return parent::setNumVuelo($numVuelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumVuelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumVuelo', array());

        return parent::getNumVuelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLPartida($lPartida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLPartida', array($lPartida));

        return parent::setLPartida($lPartida);
    }

    /**
     * {@inheritDoc}
     */
    public function getLPartida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLPartida', array());

        return parent::getLPartida();
    }

    /**
     * {@inheritDoc}
     */
    public function setLLlegada($lLlegada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLLlegada', array($lLlegada));

        return parent::setLLlegada($lLlegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getLLlegada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLLlegada', array());

        return parent::getLLlegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setHSalida($hSalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHSalida', array($hSalida));

        return parent::setHSalida($hSalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getHSalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHSalida', array());

        return parent::getHSalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setHLlegada($hLlegada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHLlegada', array($hLlegada));

        return parent::setHLlegada($hLlegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getHLlegada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHLlegada', array());

        return parent::getHLlegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdd($dateAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdd', array($dateAdd));

        return parent::setDateAdd($dateAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdd', array());

        return parent::getDateAdd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpd($dateUpd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpd', array($dateUpd));

        return parent::setDateUpd($dateUpd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpd', array());

        return parent::getDateUpd();
    }

}
