<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrHomesliderSlidesLang extends \alex\yamBundle\Entity\TrHomesliderSlidesLang implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'idHomesliderSlides', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'idLang', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'title', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'description', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'legend', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'url', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'image');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'idHomesliderSlides', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'idLang', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'title', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'description', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'legend', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'url', '' . "\0" . 'alex\\yamBundle\\Entity\\TrHomesliderSlidesLang' . "\0" . 'image');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrHomesliderSlidesLang $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdHomesliderSlides($idHomesliderSlides)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdHomesliderSlides', array($idHomesliderSlides));

        return parent::setIdHomesliderSlides($idHomesliderSlides);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdHomesliderSlides()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdHomesliderSlides();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdHomesliderSlides', array());

        return parent::getIdHomesliderSlides();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLang($idLang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLang', array($idLang));

        return parent::setIdLang($idLang);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLang()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLang();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLang', array());

        return parent::getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLegend($legend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLegend', array($legend));

        return parent::setLegend($legend);
    }

    /**
     * {@inheritDoc}
     */
    public function getLegend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLegend', array());

        return parent::getLegend();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

}
