<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrCircuito extends \alex\yamBundle\Entity\TrCircuito implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'idCircuito', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'idEmployee', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'idDepartamento', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'nombre', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'descripcionCorta', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'descripcionDetallada', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'active', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'recorrido', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'dateAdd', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'dateUpd');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'idCircuito', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'idEmployee', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'idDepartamento', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'nombre', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'descripcionCorta', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'descripcionDetallada', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'active', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'recorrido', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'dateAdd', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCircuito' . "\0" . 'dateUpd');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrCircuito $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdCircuito($idCircuito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCircuito', array($idCircuito));

        return parent::setIdCircuito($idCircuito);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCircuito()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCircuito();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCircuito', array());

        return parent::getIdCircuito();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmployee($idEmployee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmployee', array($idEmployee));

        return parent::setIdEmployee($idEmployee);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmployee()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdEmployee();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmployee', array());

        return parent::getIdEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDepartamento($idDepartamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDepartamento', array($idDepartamento));

        return parent::setIdDepartamento($idDepartamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDepartamento()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDepartamento();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDepartamento', array());

        return parent::getIdDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionCorta($descripcionCorta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionCorta', array($descripcionCorta));

        return parent::setDescripcionCorta($descripcionCorta);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionCorta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionCorta', array());

        return parent::getDescripcionCorta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionDetallada($descripcionDetallada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionDetallada', array($descripcionDetallada));

        return parent::setDescripcionDetallada($descripcionDetallada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionDetallada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionDetallada', array());

        return parent::getDescripcionDetallada();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecorrido($recorrido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecorrido', array($recorrido));

        return parent::setRecorrido($recorrido);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecorrido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecorrido', array());

        return parent::getRecorrido();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdd($dateAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdd', array($dateAdd));

        return parent::setDateAdd($dateAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdd', array());

        return parent::getDateAdd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpd($dateUpd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpd', array($dateUpd));

        return parent::setDateUpd($dateUpd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpd', array());

        return parent::getDateUpd();
    }

}
