<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrCustomization extends \alex\yamBundle\Entity\TrCustomization implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idCustomization', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idCart', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idProduct', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idAddressDelivery', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idProductAttribute', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'quantity', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'quantityRefunded', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'quantityReturned', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'inCart');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idCustomization', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idCart', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idProduct', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idAddressDelivery', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'idProductAttribute', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'quantity', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'quantityRefunded', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'quantityReturned', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCustomization' . "\0" . 'inCart');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrCustomization $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdCustomization($idCustomization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCustomization', array($idCustomization));

        return parent::setIdCustomization($idCustomization);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCustomization()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCustomization();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCustomization', array());

        return parent::getIdCustomization();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCart($idCart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCart', array($idCart));

        return parent::setIdCart($idCart);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCart()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCart();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCart', array());

        return parent::getIdCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduct($idProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduct', array($idProduct));

        return parent::setIdProduct($idProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProduct()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProduct();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduct', array());

        return parent::getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAddressDelivery($idAddressDelivery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAddressDelivery', array($idAddressDelivery));

        return parent::setIdAddressDelivery($idAddressDelivery);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAddressDelivery()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAddressDelivery();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAddressDelivery', array());

        return parent::getIdAddressDelivery();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProductAttribute($idProductAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProductAttribute', array($idProductAttribute));

        return parent::setIdProductAttribute($idProductAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProductAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProductAttribute', array());

        return parent::getIdProductAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', array($quantity));

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', array());

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityRefunded($quantityRefunded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityRefunded', array($quantityRefunded));

        return parent::setQuantityRefunded($quantityRefunded);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityRefunded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityRefunded', array());

        return parent::getQuantityRefunded();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityReturned($quantityReturned)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityReturned', array($quantityReturned));

        return parent::setQuantityReturned($quantityReturned);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityReturned()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityReturned', array());

        return parent::getQuantityReturned();
    }

    /**
     * {@inheritDoc}
     */
    public function setInCart($inCart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInCart', array($inCart));

        return parent::setInCart($inCart);
    }

    /**
     * {@inheritDoc}
     */
    public function getInCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInCart', array());

        return parent::getInCart();
    }

}
