<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrCajaDetalle extends \alex\yamBundle\Entity\TrCajaDetalle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'idCajaDetalle', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'idCaja', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'montoVirtual', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'montoReal', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'saldo', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'estado', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'dateAdd', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'dateUpd');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'idCajaDetalle', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'idCaja', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'montoVirtual', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'montoReal', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'saldo', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'estado', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'dateAdd', '' . "\0" . 'alex\\yamBundle\\Entity\\TrCajaDetalle' . "\0" . 'dateUpd');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrCajaDetalle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCajaDetalle()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCajaDetalle();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCajaDetalle', array());

        return parent::getIdCajaDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCaja($idCaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCaja', array($idCaja));

        return parent::setIdCaja($idCaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCaja', array());

        return parent::getIdCaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoVirtual($montoVirtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoVirtual', array($montoVirtual));

        return parent::setMontoVirtual($montoVirtual);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoVirtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoVirtual', array());

        return parent::getMontoVirtual();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoReal($montoReal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoReal', array($montoReal));

        return parent::setMontoReal($montoReal);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoReal', array());

        return parent::getMontoReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaldo($saldo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaldo', array($saldo));

        return parent::setSaldo($saldo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldo', array());

        return parent::getSaldo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdd($dateAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdd', array($dateAdd));

        return parent::setDateAdd($dateAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdd', array());

        return parent::getDateAdd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpd($dateUpd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpd', array($dateUpd));

        return parent::setDateUpd($dateUpd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpd', array());

        return parent::getDateUpd();
    }

}
