<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrLayeredCategory extends \alex\yamBundle\Entity\TrLayeredCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idLayeredCategory', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idShop', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idCategory', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idValue', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'type', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'position', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'filterType', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'filterShowLimit');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idLayeredCategory', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idShop', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idCategory', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'idValue', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'type', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'position', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'filterType', '' . "\0" . 'alex\\yamBundle\\Entity\\TrLayeredCategory' . "\0" . 'filterShowLimit');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrLayeredCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdLayeredCategory()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLayeredCategory();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLayeredCategory', array());

        return parent::getIdLayeredCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdShop($idShop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdShop', array($idShop));

        return parent::setIdShop($idShop);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdShop', array());

        return parent::getIdShop();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategory($idCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategory', array($idCategory));

        return parent::setIdCategory($idCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategory', array());

        return parent::getIdCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdValue($idValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdValue', array($idValue));

        return parent::setIdValue($idValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdValue', array());

        return parent::getIdValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterType($filterType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterType', array($filterType));

        return parent::setFilterType($filterType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterType', array());

        return parent::getFilterType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterShowLimit($filterShowLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterShowLimit', array($filterShowLimit));

        return parent::setFilterShowLimit($filterShowLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterShowLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterShowLimit', array());

        return parent::getFilterShowLimit();
    }

}
