<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrProductSupplier extends \alex\yamBundle\Entity\TrProductSupplier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idProductSupplier', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idProduct', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idProductAttribute', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idSupplier', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'productSupplierReference', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'productSupplierPriceTe', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idCurrency');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idProductSupplier', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idProduct', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idProductAttribute', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idSupplier', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'productSupplierReference', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'productSupplierPriceTe', '' . "\0" . 'alex\\yamBundle\\Entity\\TrProductSupplier' . "\0" . 'idCurrency');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrProductSupplier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProductSupplier()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProductSupplier();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProductSupplier', array());

        return parent::getIdProductSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduct($idProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduct', array($idProduct));

        return parent::setIdProduct($idProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduct', array());

        return parent::getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProductAttribute($idProductAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProductAttribute', array($idProductAttribute));

        return parent::setIdProductAttribute($idProductAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProductAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProductAttribute', array());

        return parent::getIdProductAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSupplier($idSupplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSupplier', array($idSupplier));

        return parent::setIdSupplier($idSupplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSupplier', array());

        return parent::getIdSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductSupplierReference($productSupplierReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductSupplierReference', array($productSupplierReference));

        return parent::setProductSupplierReference($productSupplierReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductSupplierReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductSupplierReference', array());

        return parent::getProductSupplierReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductSupplierPriceTe($productSupplierPriceTe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductSupplierPriceTe', array($productSupplierPriceTe));

        return parent::setProductSupplierPriceTe($productSupplierPriceTe);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductSupplierPriceTe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductSupplierPriceTe', array());

        return parent::getProductSupplierPriceTe();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCurrency($idCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCurrency', array($idCurrency));

        return parent::setIdCurrency($idCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCurrency', array());

        return parent::getIdCurrency();
    }

}
