<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrReferrerShop extends \alex\yamBundle\Entity\TrReferrerShop implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'idReferrer', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'idShop', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheVisitors', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheVisits', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cachePages', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheRegistrations', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheOrders', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheSales', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheRegRate', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheOrderRate');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'idReferrer', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'idShop', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheVisitors', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheVisits', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cachePages', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheRegistrations', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheOrders', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheSales', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheRegRate', '' . "\0" . 'alex\\yamBundle\\Entity\\TrReferrerShop' . "\0" . 'cacheOrderRate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrReferrerShop $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdReferrer($idReferrer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdReferrer', array($idReferrer));

        return parent::setIdReferrer($idReferrer);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdReferrer()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdReferrer();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdReferrer', array());

        return parent::getIdReferrer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdShop($idShop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdShop', array($idShop));

        return parent::setIdShop($idShop);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdShop()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdShop();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdShop', array());

        return parent::getIdShop();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheVisitors($cacheVisitors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheVisitors', array($cacheVisitors));

        return parent::setCacheVisitors($cacheVisitors);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheVisitors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheVisitors', array());

        return parent::getCacheVisitors();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheVisits($cacheVisits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheVisits', array($cacheVisits));

        return parent::setCacheVisits($cacheVisits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheVisits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheVisits', array());

        return parent::getCacheVisits();
    }

    /**
     * {@inheritDoc}
     */
    public function setCachePages($cachePages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCachePages', array($cachePages));

        return parent::setCachePages($cachePages);
    }

    /**
     * {@inheritDoc}
     */
    public function getCachePages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCachePages', array());

        return parent::getCachePages();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheRegistrations($cacheRegistrations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheRegistrations', array($cacheRegistrations));

        return parent::setCacheRegistrations($cacheRegistrations);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheRegistrations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheRegistrations', array());

        return parent::getCacheRegistrations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheOrders($cacheOrders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheOrders', array($cacheOrders));

        return parent::setCacheOrders($cacheOrders);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheOrders', array());

        return parent::getCacheOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheSales($cacheSales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheSales', array($cacheSales));

        return parent::setCacheSales($cacheSales);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheSales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheSales', array());

        return parent::getCacheSales();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheRegRate($cacheRegRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheRegRate', array($cacheRegRate));

        return parent::setCacheRegRate($cacheRegRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheRegRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheRegRate', array());

        return parent::getCacheRegRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheOrderRate($cacheOrderRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheOrderRate', array($cacheOrderRate));

        return parent::setCacheOrderRate($cacheOrderRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheOrderRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheOrderRate', array());

        return parent::getCacheOrderRate();
    }

}
