<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrThemeMeta extends \alex\yamBundle\Entity\TrThemeMeta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'idThemeMeta', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'idTheme', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'idMeta', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'leftColumn', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'rightColumn');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'idThemeMeta', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'idTheme', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'idMeta', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'leftColumn', '' . "\0" . 'alex\\yamBundle\\Entity\\TrThemeMeta' . "\0" . 'rightColumn');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrThemeMeta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdThemeMeta()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdThemeMeta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdThemeMeta', array());

        return parent::getIdThemeMeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTheme($idTheme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTheme', array($idTheme));

        return parent::setIdTheme($idTheme);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTheme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTheme', array());

        return parent::getIdTheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMeta($idMeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMeta', array($idMeta));

        return parent::setIdMeta($idMeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMeta', array());

        return parent::getIdMeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeftColumn($leftColumn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeftColumn', array($leftColumn));

        return parent::setLeftColumn($leftColumn);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeftColumn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeftColumn', array());

        return parent::getLeftColumn();
    }

    /**
     * {@inheritDoc}
     */
    public function setRightColumn($rightColumn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRightColumn', array($rightColumn));

        return parent::setRightColumn($rightColumn);
    }

    /**
     * {@inheritDoc}
     */
    public function getRightColumn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRightColumn', array());

        return parent::getRightColumn();
    }

}
