<?php

namespace Proxies\__CG__\alex\yamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrSpecificPrice extends \alex\yamBundle\Entity\TrSpecificPrice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idSpecificPrice', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idSpecificPriceRule', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCart', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idProduct', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idShop', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idShopGroup', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCurrency', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCountry', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idGroup', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCustomer', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idProductAttribute', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'price', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'fromQuantity', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'reduction', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'reductionType', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'from', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'to');
        }

        return array('__isInitialized__', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idSpecificPrice', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idSpecificPriceRule', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCart', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idProduct', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idShop', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idShopGroup', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCurrency', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCountry', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idGroup', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idCustomer', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'idProductAttribute', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'price', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'fromQuantity', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'reduction', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'reductionType', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'from', '' . "\0" . 'alex\\yamBundle\\Entity\\TrSpecificPrice' . "\0" . 'to');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrSpecificPrice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdSpecificPrice()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdSpecificPrice();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSpecificPrice', array());

        return parent::getIdSpecificPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSpecificPriceRule($idSpecificPriceRule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSpecificPriceRule', array($idSpecificPriceRule));

        return parent::setIdSpecificPriceRule($idSpecificPriceRule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSpecificPriceRule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSpecificPriceRule', array());

        return parent::getIdSpecificPriceRule();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCart($idCart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCart', array($idCart));

        return parent::setIdCart($idCart);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCart', array());

        return parent::getIdCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduct($idProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduct', array($idProduct));

        return parent::setIdProduct($idProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduct', array());

        return parent::getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdShop($idShop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdShop', array($idShop));

        return parent::setIdShop($idShop);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdShop', array());

        return parent::getIdShop();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdShopGroup($idShopGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdShopGroup', array($idShopGroup));

        return parent::setIdShopGroup($idShopGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdShopGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdShopGroup', array());

        return parent::getIdShopGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCurrency($idCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCurrency', array($idCurrency));

        return parent::setIdCurrency($idCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCurrency', array());

        return parent::getIdCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCountry($idCountry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCountry', array($idCountry));

        return parent::setIdCountry($idCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCountry', array());

        return parent::getIdCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGroup($idGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGroup', array($idGroup));

        return parent::setIdGroup($idGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGroup', array());

        return parent::getIdGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCustomer($idCustomer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCustomer', array($idCustomer));

        return parent::setIdCustomer($idCustomer);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCustomer', array());

        return parent::getIdCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProductAttribute($idProductAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProductAttribute', array($idProductAttribute));

        return parent::setIdProductAttribute($idProductAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProductAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProductAttribute', array());

        return parent::getIdProductAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromQuantity($fromQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromQuantity', array($fromQuantity));

        return parent::setFromQuantity($fromQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromQuantity', array());

        return parent::getFromQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setReduction($reduction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReduction', array($reduction));

        return parent::setReduction($reduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getReduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReduction', array());

        return parent::getReduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setReductionType($reductionType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReductionType', array($reductionType));

        return parent::setReductionType($reductionType);
    }

    /**
     * {@inheritDoc}
     */
    public function getReductionType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReductionType', array());

        return parent::getReductionType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrom($from)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrom', array($from));

        return parent::setFrom($from);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrom', array());

        return parent::getFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTo($to)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTo', array($to));

        return parent::setTo($to);
    }

    /**
     * {@inheritDoc}
     */
    public function getTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTo', array());

        return parent::getTo();
    }

}
