incluye_index:
    path:     /
    defaults: { _controller: "alexyamBundle:Incluye:index" }
    methods:  GET

incluye_show:
    path:     /{id}/show
    defaults: { _controller: "alexyamBundle:Incluye:show" }
    methods:  GET

incluye_new:
    path:     /new
    defaults: { _controller: "alexyamBundle:Incluye:new" }
    methods:  [GET, POST]

incluye_edit:
    path:     /{id}/edit
    defaults: { _controller: "alexyamBundle:Incluye:edit" }
    methods:  [GET, POST]

incluye_delete:
    path:     /{id}/delete
    defaults: { _controller: "alexyamBundle:Incluye:delete" }
    methods:  DELETE
