ruta_index:
    path:     /
    defaults: { _controller: "alexyamBundle:Ruta:index" }
    methods:  GET

ruta_show:
    path:     /{id}/show
    defaults: { _controller: "alexyamBundle:Ruta:show" }
    methods:  GET

ruta_new:
    path:     /new
    defaults: { _controller: "alexyamBundle:Ruta:new" }
    methods:  [GET, POST]

ruta_edit:
    path:     /{id}/edit
    defaults: { _controller: "alexyamBundle:Ruta:edit" }
    methods:  [GET, POST]

ruta_delete:
    path:     /{id}/delete
    defaults: { _controller: "alexyamBundle:Ruta:delete" }
    methods:  DELETE
